

MODEL_RUN_COLUMNS = list(['f1n',
                          'f2n',
                          'f3n',
                          'm1n',
                          'm2n',
                          'm3n',
                          'fattr1',
                          'fattr2',
                          'fattr3',
                          'mattr1',
                          'mattr2',
                          'mattr3',
                          'attr1',
                          'attr2',
                          'attr3',
                          'fattr',
                          'mattr',
                          'unfild1',
                          'unfild2',
                          'unfild3',
                          'unfild'
                          'deptn',
                          'lev1',
                          'lev2',
                          'lev3',
                          'fn',
                          'mn',
                          'fprop',
                          'fpct1',
                          'fpct2',
                          'fpct3',
                          'mpct1',
                          'mpct2',
                          'mpct3',
                          'fhire1',
                          'fhire2',
                          'fhire3',
                          'mhire1',
                          'mhire2',
                          'mhire3',
                          'fhire',
                          'mhire',
                          'hire',
                          'hire1',
                          'hire2',
                          'hire3',
                          'fprom1',
                          'fprom2',
                          'mprom1',
                          'mprom2',
                          'prom',
                          'prom1',
                          'prom2',
                          'fprom',
                          'mprom',
                          'ss_scen',
                          'ss_fhire1',
                          'ss_fhire2',
                          'ss_fhire3',
                          'ss_mhire1',
                          'ss_mhire2',
                          'ss_mhire3',
                          'ss_fattr1',
                          'ss_fattr2',
                          'ss_fattr3',
                          'ss_mattr1',
                          'ss_mattr2',
                          'ss_mattr3',
                          'ss_fprom1',
                          'ss_fprom2',
                          'ss_mprom1',
                          'ss_mprom2',
                          'ss_deptn_ub',
                          'ss_deptn_lb',
                          'ss_deptn_range',
                          'ss_yrs'])


EXPORT_COLUMNS_FOR_CSV = list(['hiring_rate_women_1',
                               'hiring_rate_women_2',
                               'hiring_rate_women_3',
                               'hiring_rate_men_1',
                               'hiring_rate_men_2',
                               'hiring_rate_men_3',
                               'attrition_rate_women_1',
                               'attrition_rate_women_2',
                               'attrition_rate_women_3',
                               'attrition_rate_men_1',
                               'attrition_rate_men_2',
                               'attrition_rate_men_3',
                               'future_reserved_3',
                               'future_reserved_4',
                               'future_reserved_5',
                               'female_promotion_rate_1',
                               'female_promotion_rate_2',
                               'male_promotion_rate_1',
                               'male_promotion_rate_2',
                               'dept_size_upperbound',
                               'dept_size_lowerbound',
                               'dept_size_exogenous_variation_range',
                               'duration'])


RESULTS_COLUMNS = list(['year', 'mean_f1', 'mean_f2',
                        'mean_f3', 'mean_m1',
                        'mean_m2', 'mean_m3',
                        'mean_attrition_3', 'mean_attrition_2',
                        'mean_attrition_1', 'future_reserved_0',
                        'future_reserved_1', 'mean_gendprop',
                        'mean_unfilled', 'mean_dept_size',
                        'mean_f_hire_3', 'mean_m_hire_3',
                        'mean_f_hire_2', 'mean_m_hire_2',
                        'mean_f_hire_1', 'mean_m_hire_1',
                        'mean_f_prom_3', 'mean_m_prom_3',
                        'mean_f_prom_2', 'mean_m_prom_2',
                        'mean_f_prom_1', 'mean_m_prom_1',
                        'std_f1', 'std_f2',
                        'std_f3', 'std_m1',
                        'std_m2', 'std_m3',
                        'std_attr_3', 'std_attr_2',
                        'std_attr_1', 'future_reserved_0a',
                        'future_reserved_1a', 'std_gendprop',
                        'std_unfilled', 'std_dept_size',
                        'std_f_hire_3', 'std_m_hire_3',
                        'std_f_hire_2', 'std_m_hire_2',
                        'std_f_hire_1', 'std_m_hire_1',
                        'std_f_prom_3', 'std_m_prom_3',
                        'std_f_prom_2', 'std_m_prom_2',
                        'std_f_prom_1', 'std_m_prom_1',
                        'f1_025', 'f2_025',
                        'f3_025', 'm1_025',
                        'm2_025', 'm3_025', 'attr_3_025',
                        'attr_2_025', 'attr_1_025',
                        'future_reserved_0b', 'future_reserved_1b',
                        'gendprop_025', 'unfilled_025',
                        'dept_size_025', 'f_hire_3_025',
                        'm_hire_3_025', 'f_hire_2_025',
                        'm_hire_2_025', 'f_hire_1_025',
                        'm_hire_1_025', 'f_prom_3_025',
                        'm_prom_3_025', 'f_prom_2_025',
                        'm_prom_2_025', 'f_prom_1_025',
                        'm_prom_1_025', 'f1_975',
                        'f2_975', 'f3_975',
                        'm1_975', 'm2_975',
                        'm3_975', 'attr_3_975',
                        'attr_2_975', 'attr_1_975',
                        'future_reserved_0c', 'future_reserved_1c',
                        'gendprop_975', 'unfilled_975',
                        'dept_size_975', 'f_hire_3_975',
                        'm_hire_3_975', 'f_hire_2_975',
                        'm_hire_2_975', 'f_hire_1_975',
                        'm_hire_1_975', 'f_prom_3_975',
                        'm_prom_3_975', 'f_prom_2_975',
                        'm_prom_2_975', 'f_prom_1_975',
                        'm_prom_1_975'
                        ])

FEMALE_MATRIX_COLUMNS = list(['year',
                              'mpct_f1',
                              'spct_f1',
                              'mpct_f2',
                              'spct_f2',
                              'mpct_f3',
                              'spct_f3',
                              'mpct_m1',
                              'spct_m1',
                              'mpct_m2',
                              'spct_m2',
                              'mpct_m3',
                              'spct_m3',
                              'pf1_025',
                              'pf1_975',
                              'pf2_025',
                              'pf2_975',
                              'pf3_025',
                              'pf3_975',
                              'pm1_025',
                              'pm1_975',
                              'pm2_025',
                              'pm2_975',
                              'pm3_025',
                              'pm3_975'])
